name: Review deployment

on:
  pull_request:
    types: [closed]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    stop-deployment-dev:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Stop deployment
              run: |
                curl -X 'POST' \
                  'https://ci.dev.profcomff.com/pr_stop' \
                  -H 'accept: application/json' \
                  -H 'Content-Type: application/json' \
                  -H 'Authorization: ${{ secrets.CI_DYAKOVSPACE_MSK_TOKEN }}' \
                  -d '{
                    "repo_url": "${{ github.repository }}",
                    "git_ref": "${{ github.ref }}"
                  }'

